# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from raspimouse_ros_2/ButtonValues.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ButtonValues(genpy.Message):
  _md5sum = "a4d235e22ff7d8affc3de7deb89cb505"
  _type = "raspimouse_ros_2/ButtonValues"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool front
bool mid
bool rear
bool front_toggle
bool mid_toggle
bool rear_toggle
"""
  __slots__ = ['front','mid','rear','front_toggle','mid_toggle','rear_toggle']
  _slot_types = ['bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       front,mid,rear,front_toggle,mid_toggle,rear_toggle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ButtonValues, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.front is None:
        self.front = False
      if self.mid is None:
        self.mid = False
      if self.rear is None:
        self.rear = False
      if self.front_toggle is None:
        self.front_toggle = False
      if self.mid_toggle is None:
        self.mid_toggle = False
      if self.rear_toggle is None:
        self.rear_toggle = False
    else:
      self.front = False
      self.mid = False
      self.rear = False
      self.front_toggle = False
      self.mid_toggle = False
      self.rear_toggle = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6B().pack(_x.front, _x.mid, _x.rear, _x.front_toggle, _x.mid_toggle, _x.rear_toggle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.front, _x.mid, _x.rear, _x.front_toggle, _x.mid_toggle, _x.rear_toggle,) = _get_struct_6B().unpack(str[start:end])
      self.front = bool(self.front)
      self.mid = bool(self.mid)
      self.rear = bool(self.rear)
      self.front_toggle = bool(self.front_toggle)
      self.mid_toggle = bool(self.mid_toggle)
      self.rear_toggle = bool(self.rear_toggle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6B().pack(_x.front, _x.mid, _x.rear, _x.front_toggle, _x.mid_toggle, _x.rear_toggle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.front, _x.mid, _x.rear, _x.front_toggle, _x.mid_toggle, _x.rear_toggle,) = _get_struct_6B().unpack(str[start:end])
      self.front = bool(self.front)
      self.mid = bool(self.mid)
      self.rear = bool(self.rear)
      self.front_toggle = bool(self.front_toggle)
      self.mid_toggle = bool(self.mid_toggle)
      self.rear_toggle = bool(self.rear_toggle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6B = None
def _get_struct_6B():
    global _struct_6B
    if _struct_6B is None:
        _struct_6B = struct.Struct("<6B")
    return _struct_6B
